name: aquatraceapp
description: AquaTraceApp project.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
